package com.sharedmodels;

public enum ResponseType {
    OK,
    ERROR,
    INVALID_SENDER_MAIL_ADDRESS,
    INVALID_RECEIVER_MAIL_ADDRESS,
    INVALID_MAIL_ADDRESS,
    INVALID_PAYLOAD,
    SAVING_DATA_ERROR,
    LOADING_DATA_ERROR
}
